GET:
  /: 'InvoiceController:indexAction'
  /invoice/{id}: 'InvoiceController:detailAction'
  /invoice/report: 'InvoiceController:reportAction'
  /customer/report: 'CustomerController:reportAction'
POST:
  /invoice/{id}/status: 'InvoiceController:statusAction'