GET:
  /: 'pathController:indexAction'
  /path: 'pathController:indexAction'
  /path/{to}/resource: 'pathController:resourceAction'
  /path/{to}/resource/{with}/more/{params}: 'pathController:resourceAction'
  /path/to/resource: 'pathController:resourceAction'
POST:
  /path/to/resource: 'controllerClass:method'
  /path/{to}/resource: 'controllerClass:method'
DELETE:
  /path/to/resource: 'controllerClass:method'
  /path/{to}/resource: 'controllerClass:method'